name: check

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step:
          - name: Check style
            cmd: yarn check:style
          - name: Run unit tests
            cmd: yarn test:unit
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: ${{ matrix.step.name }}
        run: ${{ matrix.step.cmd }}
